---
- hosts: kvm
  become: yes
    
  vars_files:
    - global_vars.yml

  tasks:
  - name: Get VMs list
    virt:
      command: list_vms
    register: existing_vms
    changed_when: no
    
  - name: Build list of client names
    set_fact:
      client_list: "{{ client_list | default([]) + ['client-%s' | format(item)] }}"
    loop: "{{ range(1,(global_num_of_clients+1)) | list }}"
  
  - name: Delete VM if it exists
    include_tasks: sub_delete_vm.yml
    loop: "{{ client_list }}"
    when: "item in existing_vms.list_vms"
      